#!/usr/bin/env bash
# ============================================================================
# wsl-sandbox.sh — WSL Ubuntu L2 沙箱（假 PROJECT_BASE，不碰宝塔/生产）
#
# 默认沙箱：$HOME/deploy-sandbox（Linux 原生盘，避免 /mnt/d 过慢）
# 覆盖：    export DEPLOY_SANDBOX=/path/to/sandbox
#
# Usage:
#   bash tests/wsl-sandbox.sh init
#   bash tests/wsl-sandbox.sh seed-packages
#   bash tests/wsl-sandbox.sh deploy-static financial-web
#   bash tests/wsl-sandbox.sh deploy-static official-site
#   bash tests/wsl-sandbox.sh deploy-static deepquant-web
#   bash tests/wsl-sandbox.sh deploy-api-extract
#   bash tests/wsl-sandbox.sh rollback financial-web
#   bash tests/wsl-sandbox.sh status
#   bash tests/wsl-sandbox.sh clean
#   bash tests/wsl-sandbox.sh demo    # init→seed→deploy×2→rollback→api-extract→status
# ============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DEPLOY_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
SANDBOX="${DEPLOY_SANDBOX:-$HOME/deploy-sandbox}"
PROJECT_BASE="$SANDBOX/www/wwwroot/project"
PACKAGES_DIR="$PROJECT_BASE/uploads/dist/packages"
BACKUP_BASE="$PROJECT_BASE/backup"
MAX_BACKUPS=5

# 静态站：项目名 → 相对 PROJECT_BASE 的 dist 目录
declare -A STATIC_DIST=(
  ["financial-web"]="financial/financial-web/dist"
  ["official-site"]="official-site/dist"
  ["deepquant-web"]="deepquant/web/dist"
)
declare -A STATIC_TAR=(
  ["financial-web"]="financial-web-dist.tar.gz"
  ["official-site"]="official-site-dist.tar.gz"
  ["deepquant-web"]="deepquant-web-dist.tar.gz"
)

log()  { echo -e "\033[36m[*]\033[0m $*"; }
ok()   { echo -e "\033[32m[OK]\033[0m $*"; }
warn() { echo -e "\033[33m[!]\033[0m $*"; }
err()  { echo -e "\033[31m[ERR]\033[0m $*" >&2; }

usage() {
  sed -n '2,20p' "$0" | sed 's/^# \?//'
}

cmd="${1:-}"
shift || true

case "$cmd" in
  ""|-h|--help) usage; exit 0 ;;
esac

# ── init ────────────────────────────────────────────────────────
do_init() {
  log "Init sandbox at $SANDBOX"
  mkdir -p \
    "$PACKAGES_DIR" \
    "$BACKUP_BASE" \
    "$PROJECT_BASE/financial/financial-web/dist" \
    "$PROJECT_BASE/financial/financial-api" \
    "$PROJECT_BASE/official-site/dist" \
    "$PROJECT_BASE/deepquant/web/dist" \
    "$PROJECT_BASE/deepquant/backend/package" \
    "$PROJECT_BASE/uploads/dist"

  # 沙箱专用 env（改造后可被 deploy.sh source）
  cat > "$SANDBOX/deploy.env" <<EOF
# Generated by wsl-sandbox.sh — local WSL only
PROJECT_BASE=$PROJECT_BASE
PACKAGES_DIR=$PACKAGES_DIR
BACKUP_BASE=$BACKUP_BASE
DEPLOY_LOG=$PROJECT_BASE/uploads/deploy.log
LOCK_FILE=/tmp/deploy-wsl-sandbox.lock
PG_HOST=localhost
PG_PORT=5432
PG_USER=root
PG_PASSWORD=sandbox-only
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_PASSWORD=sandbox-only
DEPLOY_DRY_RUN=1
SKIP_PREFLIGHT_REDIS=1
SKIP_PREFLIGHT_PG=1
EOF

  # 方便在沙箱内找到上游 deploy 工具
  ln -sfn "$DEPLOY_DIR" "$SANDBOX/deploy-tools"
  # 拷贝 deploy.sh 到 uploads/dist 模拟上传后布局
  cp -f "$DEPLOY_DIR/scripts/deploy.sh" "$PROJECT_BASE/uploads/dist/deploy.sh"
  chmod +x "$PROJECT_BASE/uploads/dist/deploy.sh"

  ok "Sandbox ready"
  echo "  PROJECT_BASE=$PROJECT_BASE"
  echo "  PACKAGES_DIR=$PACKAGES_DIR"
  echo "  deploy.env  =$SANDBOX/deploy.env"
}

# ── seed-packages ───────────────────────────────────────────────
do_seed() {
  [ -d "$PACKAGES_DIR" ] || { err "Run init first"; exit 1; }
  local count=0
  local dirs=()
  # 优先 packages；若无则用 dist 根，避免重复拷贝
  if ls "$DEPLOY_DIR/dist/packages"/*.tar.gz >/dev/null 2>&1; then
    dirs=("$DEPLOY_DIR/dist/packages")
  elif ls "$DEPLOY_DIR/dist"/*.tar.gz >/dev/null 2>&1; then
    dirs=("$DEPLOY_DIR/dist")
  fi
  for dir in "${dirs[@]}"; do
    [ -d "$dir" ] || continue
    for f in "$dir"/*.tar.gz; do
      [ -f "$f" ] || continue
      cp -f "$f" "$PACKAGES_DIR/"
      ok "seeded $(basename "$f")"
      count=$((count + 1))
    done
  done
  if [ "$count" -eq 0 ]; then
    warn "No tar.gz found under $DEPLOY_DIR/dist — create a tiny fixture"
    local tmp
    tmp=$(mktemp -d)
    echo '<html>sandbox-fixture</html>' > "$tmp/index.html"
    tar -czf "$PACKAGES_DIR/financial-web-dist.tar.gz" -C "$tmp" .
    rm -rf "$tmp"
    ok "created fixture financial-web-dist.tar.gz"
  fi
  ls -lh "$PACKAGES_DIR"
}

find_tar() {
  local pattern="$1"
  ls -t "$PACKAGES_DIR"/$pattern 2>/dev/null | head -1 || true
}

backup_dir_tree() {
  local name="$1" dist_dir="$2"
  local backup_dir="$BACKUP_BASE/$name"
  local ts
  ts=$(date +%Y%m%d-%H%M%S)
  if [ ! -d "$dist_dir" ] || [ -z "$(ls -A "$dist_dir" 2>/dev/null || true)" ]; then
    warn "$name: nothing to backup"
    return 0
  fi
  mkdir -p "$backup_dir"
  tar czf "$backup_dir/$ts.tar.gz" -C "$(dirname "$dist_dir")" "$(basename "$dist_dir")"
  ok "backup $name → $backup_dir/$ts.tar.gz"
  local n
  n=$(ls -1 "$backup_dir"/*.tar.gz 2>/dev/null | wc -l | tr -d ' ')
  if [ "$n" -gt "$MAX_BACKUPS" ]; then
    ls -t "$backup_dir"/*.tar.gz | tail -n +"$((MAX_BACKUPS + 1))" | xargs -r rm -f
  fi
}

# ── deploy-static ───────────────────────────────────────────────
do_deploy_static() {
  local name="${1:-}"
  [ -n "$name" ] || { err "Usage: deploy-static <financial-web|official-site|deepquant-web>"; exit 1; }
  local rel="${STATIC_DIST[$name]:-}"
  local tar_name="${STATIC_TAR[$name]:-}"
  [ -n "$rel" ] || { err "Unknown static project: $name"; exit 1; }

  local dest="$PROJECT_BASE/$rel"
  local tar
  tar=$(find_tar "$tar_name")
  [ -n "$tar" ] || { err "Missing $tar_name in $PACKAGES_DIR (seed-packages first)"; exit 1; }

  backup_dir_tree "$name" "$dest"
  mkdir -p "$dest"
  rm -rf "${dest:?}"/*
  tar xzf "$tar" -C "$dest"
  ok "deployed $name → $dest ($(du -sh "$dest" | cut -f1))"
  # 首次部署无「旧版」可备时，额外留一份当前版，便于立刻练习 rollback
  local backup_dir="$BACKUP_BASE/$name"
  if [ ! -d "$backup_dir" ] || [ -z "$(ls -A "$backup_dir"/*.tar.gz 2>/dev/null || true)" ]; then
    backup_dir_tree "$name" "$dest"
    ok "seeded first rollback point for $name"
  fi
}

# ── rollback（单项目 / 多项目 / all + 确认）─────────────────────
confirm_or_abort() {
  local prompt="$1"
  if [ "${ASSUME_YES:-0}" = "1" ]; then
    warn "ASSUME_YES=1：跳过确认"
    return 0
  fi
  local confirm
  read -rp "  $prompt 请输入 yes 继续: " confirm
  [ "$confirm" = "yes" ] || { warn "已取消"; return 1; }
  return 0
}

do_rollback() {
  # 用法:
  #   rollback financial-web
  #   rollback financial-web,official-site
  #   rollback all
  #   rollback financial-web --yes
  local spec="${1:-}"
  local yes_flag="${2:-}"
  [ -n "$spec" ] || { err "Usage: rollback <project|proj1,proj2|all> [--yes]"; exit 1; }
  if [ "$yes_flag" = "--yes" ] || [ "$spec" = "--yes" ]; then
    ASSUME_YES=1
  fi
  [ "$spec" = "--yes" ] && { err "Usage: rollback <project|...> [--yes]"; exit 1; }

  local targets=()
  if [ "$spec" = "all" ]; then
    local name
    for name in "${!STATIC_DIST[@]}"; do
      if ls "$BACKUP_BASE/$name"/*.tar.gz >/dev/null 2>&1; then
        targets+=("$name")
      else
        warn "跳过 $name（无备份）"
      fi
    done
  elif [[ "$spec" == *","* ]]; then
    local IFS=',' part
    for part in $spec; do
      part=$(echo "$part" | xargs)
      [ -z "$part" ] && continue
      targets+=("$part")
    done
  else
    targets=("$spec")
  fi

  [ ${#targets[@]} -eq 0 ] && { err "没有可回滚的项目"; exit 1; }

  echo ""
  hr() { echo "────────────────────────────────────────────────"; }
  hr
  echo "  即将回滚："
  local name latest
  for name in "${targets[@]}"; do
    local rel="${STATIC_DIST[$name]:-}"
    [ -n "$rel" ] || { err "未知静态项目: $name"; exit 1; }
    latest=$(ls -t "$BACKUP_BASE/$name"/*.tar.gz 2>/dev/null | head -1 || true)
    [ -n "$latest" ] || { err "$name 无备份"; exit 1; }
    echo "  • $name → $(basename "$latest" .tar.gz)"
  done
  hr
  confirm_or_abort "确认回滚以上 ${#targets[@]} 个项目？" || exit 1

  for name in "${targets[@]}"; do
    local dest="$PROJECT_BASE/${STATIC_DIST[$name]}"
    local backup_dir="$BACKUP_BASE/$name"
    latest=$(ls -t "$backup_dir"/*.tar.gz 2>/dev/null | head -1)
    backup_dir_tree "$name" "$dest"
    rm -rf "$dest"
    mkdir -p "$(dirname "$dest")"
    tar xzf "$latest" -C "$(dirname "$dest")"
    ok "rolled back $name from $(basename "$latest")"
  done
}

# 通过真实 deploy.sh 回滚（验证服务器脚本逻辑）
do_rollback_via_deploy() {
  local spec="${1:-financial-web}"
  local yes="${2:---yes}"
  [ -f "$SANDBOX/deploy.env" ] || { err "Run init first"; exit 1; }
  # 重新拷贝最新 deploy.sh
  cp -f "$DEPLOY_DIR/scripts/deploy.sh" "$PROJECT_BASE/uploads/dist/deploy.sh"
  export DEPLOY_ENV_FILE="$SANDBOX/deploy.env"
  export DEPLOY_DRY_RUN=1
  log "Calling deploy.sh $spec --rollback=latest $yes (DEPLOY_ENV_FILE=$DEPLOY_ENV_FILE)"
  bash "$DEPLOY_DIR/scripts/deploy.sh" "$spec" --rollback=latest $yes
}

# ── deploy-api-extract（只解压，不跑 systemd/migrate）──────────
do_deploy_api_extract() {
  local tar
  tar=$(find_tar "financial-api-*.tar.gz")
  [ -n "$tar" ] || { err "No financial-api-*.tar.gz — pack + seed first"; exit 1; }
  local target="$PROJECT_BASE/financial/financial-api"
  mkdir -p "$target"
  backup_dir_tree "financial-api" "$target/package"
  # 与服务器一致：解压出 package/
  tar xzf "$tar" -C "$target"
  ok "extracted API to $target/package"
  if [ -f "$target/package/VERSION" ]; then
    ok "VERSION:"
    cat "$target/package/VERSION"
  else
    warn "no VERSION file in package"
  fi
  if [ -f "$target/package/deploy-financial-api.sh" ]; then
    ok "deploy-financial-api.sh present (dry-run: not executing full deploy)"
  fi
}

# ── status ──────────────────────────────────────────────────────
do_status() {
  echo ""
  echo "  SANDBOX      = $SANDBOX"
  echo "  PROJECT_BASE = $PROJECT_BASE"
  echo ""
  echo "  Packages:"
  ls -lh "$PACKAGES_DIR" 2>/dev/null || echo "    (empty)"
  echo ""
  echo "  Trees:"
  for name in financial-web official-site deepquant-web; do
    local d="$PROJECT_BASE/${STATIC_DIST[$name]}"
    if [ -d "$d" ] && [ -n "$(ls -A "$d" 2>/dev/null || true)" ]; then
      echo "    $name: $(du -sh "$d" | cut -f1)  ($d)"
    else
      echo "    $name: (empty)"
    fi
  done
  if [ -d "$PROJECT_BASE/financial/financial-api/package" ]; then
    echo "    financial-api: $(du -sh "$PROJECT_BASE/financial/financial-api/package" | cut -f1)"
  fi
  echo ""
  echo "  Backups:"
  find "$BACKUP_BASE" -name '*.tar.gz' 2>/dev/null | sort || echo "    (none)"
  echo ""
}

# ── clean ───────────────────────────────────────────────────────
do_clean() {
  warn "Removing $SANDBOX"
  rm -rf "$SANDBOX"
  ok "cleaned"
}

# ── lock demo（验证 flock 思路，不调用真实 deploy）─────────────
do_lock_demo() {
  local lock="$SANDBOX/deploy.lock"
  mkdir -p "$SANDBOX"
  exec 200>"$lock"
  if ! flock -n 200; then
    err "lock held (as expected if another holder exists)"
    exit 1
  fi
  ok "acquired lock $lock — holding 8s (run lock-demo in another terminal to see fail)"
  sleep 8
  ok "released"
}

case "$cmd" in
  init)               do_init ;;
  seed-packages|seed) do_seed ;;
  deploy-static)      do_deploy_static "${1:-}" ;;
  rollback)           do_rollback "${1:-}" "${2:-}" ;;
  rollback-via-deploy) do_rollback_via_deploy "${1:-financial-web}" "${2:---yes}" ;;
  deploy-api-extract|deploy-api-dry) do_deploy_api_extract ;;
  status)             do_status ;;
  clean)              do_clean ;;
  lock-demo)          do_lock_demo ;;
  demo)
    export ASSUME_YES=1
    do_init
    do_seed
    do_deploy_static "financial-web"
    do_deploy_static "official-site" || warn "official-site pack missing"
    do_deploy_static "financial-web"
    do_deploy_static "official-site" || true
    # 单项目回滚
    do_rollback "financial-web" --yes
    # 多项目回滚
    do_rollback "financial-web,official-site" --yes || warn "multi rollback partial"
    # 真实 deploy.sh 回滚路径
    do_rollback_via_deploy "financial-web,official-site" --yes || warn "deploy.sh rollback failed"
    do_deploy_api_extract || warn "API extract skipped"
    do_status
    ok "demo flow complete — run: bash tests/wsl-sandbox.sh clean"
    ;;
  *)
    err "Unknown command: $cmd"
    usage
    exit 1
    ;;
esac
